services:
  helloric_ui_com:
    image: harbor.hb.dfki.de/helloric/ui_com:x64_jazzy_001
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
    environment:
      PYTHONUNBUFFERED: 1
      ZENOH_CONFIG_OVERRIDE: >-
          connect/endpoints=["tcp/host.docker.internal:${ZENOH_ROUTER_PORT}"];mode="client"
    extra_hosts:
      - "host.docker.internal:host-gateway"
